### ISSUE TITLE
wolfssl + tokio

### ISSUE THREAD

**Issue by incker** [expressvpn/wolfssl-sys#26]
Hello!

I think it is more a question or feature request.
is there any crate wrapper to asyncify wolfssl for tokio?

**Comment by expressvpn-pang-t** [comment]
Hi!

Unfortunately such an async wrapper (to my current knowledge) does not exist yet.

However, we eventually do want to asyncify `wolfssl-sys`.

**Comment by expressvpn-pete-m** [comment]
Hi @incker,

Thanks for reaching out! 😊 

There aren't any wrappers to do this with WolfSSL as far we are aware. There is a pretty full implementation put together by AgileBits that uses the WolfSSL OpenSSL compatibility bindings that might be able to get you close to what you need.

For this crate, the goal is just to be a lightweight `-sys` wrapper so that when other people create more fully feature implementations of WolfSSL, we can all share and enhance the same base.

That said, although we don't have a timetable for this other than "in the not too distant future", we are looking at putting together our own high level crate for WolfSSL that will specifically be designed to place nice with Tokio 😊
